services:
  app:
    name: maps-scraper
    type: worker
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: python google_maps_scraper.py
    python: 3.9
