services:
  maps-scraper:
    type: worker
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && playwright install --with-deps
    startCommand: python google_maps_scraper.py
    pythonVersion: 3.9
